-- CreateEnum
CREATE TYPE "PropertyHistoryAction" AS ENUM ('CREATED', 'DRAFT_SAVED', 'SUBMITTED', 'APPROVED', 'REJECTED', 'REQUESTED_CHANGES', 'PUBLISHED', 'LEAD_RECORDED', 'VIEW_RECORDED');
CREATE TYPE "LeadType" AS ENUM ('WHATSAPP', 'CALL', 'INSPECTION', 'SAVE', 'SHARE');

-- AlterTable Property: new columns with defaults
ALTER TABLE "Property" ALTER COLUMN "title" SET DEFAULT '';
ALTER TABLE "Property" ALTER COLUMN "description" SET DEFAULT '';
ALTER TABLE "Property" ALTER COLUMN "address" SET DEFAULT '';
ALTER TABLE "Property" ALTER COLUMN "city" SET DEFAULT '';
ALTER TABLE "Property" ALTER COLUMN "country" SET DEFAULT '';
ALTER TABLE "Property" ALTER COLUMN "price" SET DEFAULT 0;
ALTER TABLE "Property" ALTER COLUMN "bedrooms" SET DEFAULT 0;
ALTER TABLE "Property" ALTER COLUMN "bathrooms" SET DEFAULT 0;
ALTER TABLE "Property" ALTER COLUMN "squareFootage" SET DEFAULT 0;
ALTER TABLE "Property" ALTER COLUMN "amenities" SET DEFAULT '[]';
ALTER TABLE "Property" ALTER COLUMN "images" SET DEFAULT '[]';
ALTER TABLE "Property" ALTER COLUMN "status" SET DEFAULT 'DRAFT';

ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "state" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "propertyType" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "toilets" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "squareMeters" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "landSize" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "furnishing" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "parkingSpaces" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "floorNumber" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "totalFloors" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "yearBuilt" INTEGER;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "coverImage" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "videoUrl" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "tour360Url" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "landmark" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "neighborhood" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "estateName" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "serviceCharge" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "agencyFee" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "cautionFee" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "inspectionFee" DOUBLE PRECISION;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "contactPhone" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "contactWhatsapp" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "contactEmail" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "draftStep" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "lastSavedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "listingViews" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "totalLeads" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "rejectionReason" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "adminNote" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "reviewedById" TEXT;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "approvedAt" TIMESTAMP(3);

UPDATE "Property" SET "status" = 'PUBLISHED' WHERE "status" = 'APPROVED';

CREATE TABLE IF NOT EXISTS "PropertyHistory" (
    "id" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "userId" TEXT,
    "action" "PropertyHistoryAction" NOT NULL,
    "fromStatus" "PropertyStatus",
    "toStatus" "PropertyStatus",
    "note" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PropertyHistory_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "PropertyLead" (
    "id" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "userId" TEXT,
    "leadType" "LeadType" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "PropertyLead_pkey" PRIMARY KEY ("id")
);

DO $$ BEGIN
  ALTER TABLE "Property" ADD CONSTRAINT "Property_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PropertyHistory" ADD CONSTRAINT "PropertyHistory_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PropertyHistory" ADD CONSTRAINT "PropertyHistory_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TABLE "PropertyLead" ADD CONSTRAINT "PropertyLead_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
